/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Certificate } from "./Certificate";
export * as factories from "./factories";
export { Certificate__factory } from "./factories/Certificate__factory";
